// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlQbZhQdUMzAzrSS8isAOgIX_AnNaDXI',
    appId: '1:644534180818:ios:807c886efb52a7487d460b',
    messagingSenderId: '644534180818',
    projectId: 'mychatapp-363a1',
    storageBucket: 'mychatapp-363a1.firebasestorage.app',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZlQbZhQdUMzAzrSS8isAOgIX_AnNaDXI',
    appId: '1:644534180818:ios:807c886efb52a7487d460b',
    messagingSenderId: '644534180818',
    projectId: 'mychatapp-363a1',
    storageBucket: 'mychatapp-363a1.firebasestorage.app',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTRvVfFYt6rrrrLUSV_5hu08ybLNSItH4',
    appId: '1:644534180818:web:9d3c44e4301ad4fa7d460b',
    messagingSenderId: '644534180818',
    projectId: 'mychatapp-363a1',
    authDomain: 'mychatapp-363a1.firebaseapp.com',
    storageBucket: 'mychatapp-363a1.firebasestorage.app',
    measurementId: 'G-PYW5PRD0L7',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTRvVfFYt6rrrrLUSV_5hu08ybLNSItH4',
    appId: '1:644534180818:web:9d3c44e4301ad4fa7d460b',
    messagingSenderId: '644534180818',
    projectId: 'mychatapp-363a1',
    authDomain: 'mychatapp-363a1.firebaseapp.com',
    storageBucket: 'mychatapp-363a1.firebasestorage.app',
    measurementId: 'G-PYW5PRD0L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3u4d8BHDqI3kqGiAUZvI3rTsrOxryles',
    appId: '1:644534180818:android:3785a209f84ac4867d460b',
    messagingSenderId: '644534180818',
    projectId: 'mychatapp-363a1',
    storageBucket: 'mychatapp-363a1.firebasestorage.app',
  );

}